In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
%matplotlib inline

In [2]:
df=pd.read_excel("/kaggle/input/buy-or-not-purchase-intent-prediction-challenge/Training Dataset.xlsx")

In [3]:
df.head()

,ID,Start Date,End Date,Estimated Win Rate,Price,Customer Segment 1,Customer Segment 2,Customer Segment 3,Customer Segment 4,Customer Segment 5,Unit Number,Activity 1,Activity 2,Country,City,Product,Competitor,Marketing Source,Division,Manager,Techincal Manager,Customer ID,Result
0,1,2021-03-16,2021-04-20,0.75,3270.83,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,VUI150,AAB162,PWH228,PN73,NaN,NaN,426201,0
1,2,2021-03-18,2021-08-16,0.50,3772.74,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,WWQ705,AAB162,PWH228,PN73,NaN,NaN,572438,0
2,3,2021-04-01,2021-09-03,0.10,2230.27,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,VUI150,AAB162,PWH228,PN73,NaN,NaN,2080929,0
3,4,2021-04-08,2021-07-01,0.50,5000.00,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,WWQ705,AAB162,PWH228,PN73,NaN,NaN,959569,0
4,5,2021-03-17,2023-08-24,0.20,51506.23,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,OXC337,AAB162,PWH228,EM41,NaN,NaN,229558,0

In [4]:
df.drop(columns=["ID","Customer ID","Manager","Techincal Manager"],axis=1,inplace=True)

In [5]:
df.shape

(177086, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177086 entries, 0 to 177085
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Start Date          177086 non-null  datetime64[ns]
 1   End Date            177086 non-null  datetime64[ns]
 2   Estimated Win Rate  166527 non-null  float64
 3   Price               177086 non-null  float64
 4   Customer Segment 1  177086 non-null  object
 5   Customer Segment 2  177086 non-null  object
 6   Customer Segment 3  177086 non-null  object
 7   Customer Segment 4  177086 non-null  object
 8   Customer Segment 5  177086 non-null  object
 9   Unit Number         177086 non-null  int64
 10  Activity 1          177086 non-null  object
 11  Activity 2          177086 non-null  object
 12  Country             177086 non-null  object
 13  City                177030 non-null  object
 14  Product             177044 non-null  object
 15  Competitor          175980 non-null  object
 16  Marketing Source    177035 non-null  object
 17  Division            177085 non-null  object
 18  Result              177086 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(2), object(13)
memory usage: 25.7+ MB

In [7]:
mean=df["Estimated Win Rate"].mean()
df["Estimated Win Rate"]=df["Estimated Win Rate"].fillna(mean)

mode=df["City"].mode()[0]
df["City"]=df["City"].fillna(mode)


mode=df["Product"].mode()[0]
df["Product"]=df["Product"].fillna(mode)

mode=df["Competitor"].mode()[0]
df["Competitor"]=df["Competitor"].fillna(mode)

mode=df["Marketing Source"].mode()[0]
df["Marketing Source"]=df["Marketing Source"].fillna(mode)

mode=df["Division"].mode()[0]
df["Division"]=df["Division"].fillna(mode)

In [8]:
df.isnull().sum()

Start Date            0
End Date              0
Estimated Win Rate    0
Price                 0
Customer Segment 1    0
Customer Segment 2    0
Customer Segment 3    0
Customer Segment 4    0
Customer Segment 5    0
Unit Number           0
Activity 1            0
Activity 2            0
Country               0
City                  0
Product               0
Competitor            0
Marketing Source      0
Division              0
Result                0
dtype: int64

In [9]:
df['Start Date'] = pd.to_datetime(df['Start Date'])
df['End Date'] = pd.to_datetime(df['End Date'])

In [10]:
df['Start_Year'] = df['Start Date'].dt.year
df['Start_Month'] = df['Start Date'].dt.month
df['Start_Day'] = df['Start Date'].dt.day
df['Start_Weekday'] = df['Start Date'].dt.weekday  # Monday=0

# From End Date
df['End_Year'] = df['End Date'].dt.year
df['End_Month'] = df['End Date'].dt.month
df['End_Day'] = df['End Date'].dt.day
df['End_Weekday'] = df['End Date'].dt.weekday

In [11]:
df.drop(columns=["Start Date","End Date"],axis=1,inplace=True)

In [12]:
df.head()

,Estimated Win Rate,Price,Customer Segment 1,Customer Segment 2,Customer Segment 3,Customer Segment 4,Customer Segment 5,Unit Number,Activity 1,Activity 2,Country,City,Product,Competitor,Marketing Source,Division,Result,Start_Year,Start_Month,Start_Day,Start_Weekday,End_Year,End_Month,End_Day,End_Weekday
0,0.75,3270.83,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,VUI150,AAB162,PWH228,PN73,0,2021,3,16,1,2021,4,20,1
1,0.50,3772.74,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,WWQ705,AAB162,PWH228,PN73,0,2021,3,18,3,2021,8,16,0
2,0.10,2230.27,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,VUI150,AAB162,PWH228,PN73,0,2021,4,1,3,2021,9,3,4
3,0.50,5000.00,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,WWQ705,AAB162,PWH228,PN73,0,2021,4,8,3,2021,7,1,3
4,0.20,51506.23,I,A,AA,CCC,AB,1,EF,IJ,JKL,SME278,OXC337,AAB162,PWH228,EM41,0,2021,3,17,2,2023,8,24,3

In [13]:
cat_cols=df.select_dtypes(include=["object"]).columns

mappings = {}

for col in cat_cols:
    codes, uniques = pd.factorize(df[col])
    df[col] = codes
    mappings[col] = dict(enumerate(uniques))

# Show mappings for each column
for col, mapping in mappings.items():
    print(f"{col} mapping: {mapping}\n")

Customer Segment 1 mapping: {0: 'I', 1: 'F', 2: 'G', 3: 'J', 4: 'K', 5: 'H', 6: 'L'}

Customer Segment 2 mapping: {0: 'A', 1: 'C', 2: 'B', 3: 'D', 4: 'E'}

Customer Segment 3 mapping: {0: 'AA', 1: 'BB', 2: 'EE', 3: 'CC', 4: 'DD', 5: 'FF', 6: 'GG'}

Customer Segment 4 mapping: {0: 'CCC', 1: 'BBB', 2: 'AAA', 3: 'DDD'}

Customer Segment 5 mapping: {0: 'AB', 1: 'CD'}

Activity 1 mapping: {0: 'EF', 1: 'GH'}

Activity 2 mapping: {0: 'IJ', 1: 'KL'}

Country mapping: {0: 'JKL', 1: 'VWX', 2: 'DEF', 3: 'PQR', 4: 'STU', 5: 'MNO', 6: 'ABC', 7: 'GHI'}

City mapping: {0: 'SME278', 1: 'YGS695', 2: 'IMF435', 3: 'FUH372', 4: 'SAO455', 5: 'HJR277', 6: 'QSW239', 7: 'JMJ759', 8: 'IQH555', 9: 'VFR844', 10: 'IKB920', 11: 'XJJ260', 12: 'EOH323', 13: 'QGD703', 14: 'EAS271', 15: 'LPJ621', 16: 'VME946', 17: 'ISH651', 18: 'UCX355', 19: 'ISG124', 20: 'DIF777', 21: 'LJK362', 22: 'LNO392', 23: 'OHG455', 24: 'GHK468'}

Product mapping: {0: 'VUI150', 1: 'WWQ705', 2: 'OXC337', 3: 'BNX965', 4: 'OJK516', 5: 'RWN676', 6: 'CAA301', 7: 'ELT244', 8: 'IYR218', 9: 'JNQ525', 10: 'ASH122', 11: 'QKL122', 12: 'BZD102', 13: 'DDH740', 14: 'TIB104', 15: 'SBS339', 16: 'AHU981', 17: 'UKC231', 18: 'IEJ418', 19: 'RPZ341', 20: 'CYK149', 21: 'PCS186', 22: 'RJX133', 23: 'IDK592', 24: 'EFK842', 25: 'LMH911', 26: 'ZZG387', 27: 'AHS534', 28: 'TWV318', 29: 'PBD708', 30: 'OQJ243', 31: 'ZZZ772', 32: 'KFD575', 33: 'WQF420', 34: 'YET951', 35: 'SEQ701', 36: 'QUJ298', 37: 'PFE165', 38: 'GBA587', 39: 'LUU257', 40: 'VSY183', 41: 'WGK163', 42: 'DJF344', 43: 'TAS278', 44: 'VTJ209', 45: 'OPJ875', 46: 'WFE973', 47: 'KLV616', 48: 'TUH861', 49: 'ACC683', 50: 'XAZ377', 51: 'IMI166', 52: 'UXG876', 53: 'MRG361', 54: 'IGZ116', 55: 'ZRB471', 56: 'ZQP924', 57: 'PDQ165', 58: 'BMO904', 59: 'OUL192', 60: 'WGG471', 61: 'OQB899', 62: 'HSI255', 63: 'YHK552', 64: 'QPQ856', 65: 'TZU589', 66: 'KFD782', 67: 'PHK858', 68: 'KWK188', 69: 'MKZ775', 70: 'FAN114', 71: 'NNJ260', 72: 'OSN232', 73: 'CSE619', 74: 'BKO595', 75: 'KGW789', 76: 'YNG481', 77: 'YRG284', 78: 'LMM602', 79: 'GDY463', 80: 'IBP688', 81: 'VLQ786', 82: 'FAS572', 83: 'HDC411', 84: 'PVX177', 85: 'LGT873', 86: 'LPV465', 87: 'EIA804', 88: 'FNM467', 89: 'ANS347', 90: 'JNM570', 91: 'YBJ977', 92: 'FXB964', 93: 'UJB816', 94: 'PQH477', 95: 'QZL969', 96: 'JUZ210', 97: 'LCC576', 98: 'YNA955', 99: 'UHP248', 100: 'CDM135', 101: 'OYN577', 102: 'UAA477', 103: 'QMT661', 104: 'YKJ437', 105: 'ZQQ966', 106: 'COA303', 107: 'HET499', 108: 'AVI660', 109: 'PIZ994', 110: 'ZRH313', 111: 'UVF182', 112: 'FTK739', 113: 'JGW462', 114: 'FDN226', 115: 'HZK779', 116: 'OUC817', 117: 'RIE942', 118: 'HCC667', 119: 'DDV247', 120: 'JQH112', 121: 'YIZ756', 122: 'FGS646', 123: 'NHN988', 124: 'OBT722', 125: 'LNH159', 126: 'WXO485', 127: 'GTU238', 128: 'NPQ190', 129: 'ULE624', 130: 'MSO587', 131: 'JQU532', 132: 'GUW188', 133: 'JIZ597', 134: 'GON921', 135: 'OQP495', 136: 'USV132', 137: 'AIY965', 138: 'WLE181', 139: 'SEL594', 140: 'LPG801', 141: 'POB908', 142: 'IVR934', 143: 'ABC540', 144: 'JLS722', 145: 'URO471', 146: 'HBX552', 147: 'AIA259', 148: 'IVT826', 149: 'YCL123', 150: 'AFU931', 151: 'QXZ126', 152: 'EEG558', 153: 'SSE923', 154: 'NEY490', 155: 'HFL364', 156: 'AIW477', 157: 'LES327', 158: 'WAQ326', 159: 'FYX693', 160: 'IYD819', 161: 'XEV673', 162: 'AIH123'}

Competitor mapping: {0: 'AAB162', 1: 'VIQ264', 2: 'MWR693', 3: 'SVE211', 4: 'UTG383', 5: 'QJI131', 6: 'AOV771', 7: 'MAA248', 8: 'BTA951', 9: 'QXP367', 10: 'HUN156', 11: 'JRW278', 12: 'KTT271', 13: 'SYF894', 14: 'PPX925', 15: 'RRN963', 16: 'TNP148', 17: 'KVW306', 18: 'YPX212', 19: 'NZZ386', 20: 'LXL171', 21: 'CIP753', 22: 'RZQ856', 23: 'CNB950', 24: 'PSX800', 25: 'QSG333', 26: 'JZQ408', 27: 'FJI920', 28: 'YYZ249', 29: 'GIB853', 30: 'SLZ258', 31: 'NLQ530', 32: 'CCP922', 33: 'MOZ636', 34: 'JTS406', 35: 'NRF170', 36: 'BOT871', 37: 'HPO378', 38: 'CNJ469', 39: 'XFS613', 40: 'TGQ292', 41: 'MJD245', 42: 'TXK571', 43: 'XXJ296', 44: 'SCF609', 45: 'QNJ715', 46: 'XCE470', 47: 'YMS626', 48: 'RQO768', 49: 'AKH697', 50: 'BET423', 51: 'CAS622', 52: 'YWU613', 53: 'BVK186', 54: 'QMB418', 55: 'HDM269', 56: 'AVE616', 57: 'ZOR910', 58: 'RKL973', 59: 'YRQ316', 60: 'ZFP177', 61: 'NTE345', 62: 'BHI181', 63: 'TEK100', 64: 'ETI863', 65: 'LJO441', 66: 'ZSN804', 67: 'BUS769', 68: 'OKH293', 69: 'VUK331', 70: 'KJM686', 71: 'GMF546', 72: 'ATQ695', 73: 'BGW277', 74: 'GUC507', 75: 'JWT223', 76: 'LAM323', 77: 'FAN212', 78: 'ZEB711', 79: 'NKR869', 80: 'TUM800', 81: 'RLK124', 82: 'WXS254', 83: 'NMY642', 84: 'WYC966', 85: 'IUI101', 86: 'XSU947', 87: 'UHL345', 88: 'WMG635', 89: 'KJR298', 90: 'IFA552', 91: 'OXQ382', 92: 'LXP577', 93: 'DKP327', 94: 'ZTZ142', 95: 'TOB942', 96: 'RMI326', 97: 'VVG501', 98: 'RHK944', 99: 'WYN867', 100: 'LEI607', 101: 'WKF684', 102: 'VTY502', 103: 'WNS797', 104: 'USW449', 105: 'VKJ814', 106: 'QHB704', 107: 'WBE382', 108: 'MLV820', 109: 'QVV120', 110: 'HVI922', 111: 'MZX337', 112: 'DAQ879', 113: 'AGI970', 114: 'PNC359', 115: 'PZT210', 116: 'ZMR943', 117: 'UXI456', 118: 'EVX603', 119: 'VWC413', 120: 'GWN856', 121: 'EIF866', 122: 'YQE168', 123: 'RSL270', 124: 'HAH232', 125: 'LLG805', 126: 'VIO755', 127: 'FFZ926', 128: 'OZY811', 129: 'PET383', 130: 'ZIR827', 131: 'DQC369', 132: 'HRM796', 133: 'LCH696', 134: 'CND961', 135: 'AUD215', 136: 'MEH568', 137: 'GEM994', 138: 'DIA785', 139: 'ADA228', 140: 'ZOO701', 141: 'RAF353', 142: 'HXA336', 143: 'BZP802', 144: 'PZE123', 145: 'IJZ437', 146: 'AGJ576', 147: 'DMT849', 148: 'UHY242', 149: 'ZVX484', 150: 'XLP876', 151: 'ZWF265', 152: 'LGU938', 153: 'MAO174', 154: 'HWA411', 155: 'WNQ578', 156: 'NFZ970', 157: 'DEH909', 158: 'LTK810', 159: 'HAX691', 160: 'CGV732', 161: 'LIB473', 162: 'ZQJ711', 163: 'BIA973', 164: 'EIX177', 165: 'MIL697', 166: 'CBT270', 167: 'IRM203', 168: 'EYH512', 169: 'MFH136', 170: 'LBB958', 171: 'MUZ743', 172: 'MSC372', 173: 'OZU499', 174: 'FKU295', 175: 'VVH130', 176: 'AXH403', 177: 'KTR678', 178: 'SZC533', 179: 'FBT889', 180: 'GNK640', 181: 'XME756', 182: 'DSP174', 183: 'KEP552', 184: 'DNM326', 185: 'VZA212'}

Marketing Source mapping: {0: 'PWH228', 1: 'ZRG339', 2: 'QJE383', 3: 'KAD664', 4: 'ZDL229', 5: 'DGO863', 6: 'MHN746', 7: 'XSX741', 8: 'TMQ144', 9: 'URH199', 10: 'GJG862', 11: 'QVB936', 12: 'NEP704', 13: 'YHC258', 14: 'MUJ145', 15: 'UUK616', 16: 'EGH114', 17: 'HIT554', 18: 'KRF933', 19: 'POU893', 20: 'DEX621', 21: 'HJJ571', 22: 'FSX422', 23: 'BSW890', 24: 'HKQ899', 25: 'OBF888', 26: 'LZK497', 27: 'UUH636', 28: 'FHJ361', 29: 'ROJ332', 30: 'ELX843', 31: 'RPY649', 32: 'WTC622', 33: 'JUN496', 34: 'OMV625', 35: 'BDP417', 36: 'CML525', 37: 'BYM722', 38: 'ULX571', 39: 'CPM675', 40: 'TCN370', 41: 'MDU698', 42: 'JWP393', 43: 'RMD495', 44: 'FXW629'}

Division mapping: {0: 'PN73', 1: 'EM41', 2: 'YE43', 3: 'UW72', 4: 'SX68', 5: 'QO91', 6: 'PY27', 7: 'JZ93', 8: 'UT88', 9: 'HU70', 10: 'FY21', 11: 'WL88', 12: 'MB97', 13: 'WF71', 14: 'FA29', 15: 'CU52', 16: 'OF62', 17: 'XX96', 18: 'BP40', 19: 'DD49', 20: 'FK51', 21: 'DF88', 22: 'AB49', 23: 'FA95', 24: 'CP82', 25: 'DI56', 26: 'HJ14', 27: 'LS34', 28: 'EU68', 29: 'RZ94', 30: 'IX49', 31: 'ZS14', 32: 'EU77', 33: 'XK17', 34: 'RS26', 35: 'WA83', 36: 'FV96', 37: 'FN20', 38: 'HI71', 39: 'DV21', 40: 'RU77', 41: 'FU43', 42: 'FT35', 43: 'GR79'}

In [14]:
df["Result"].value_counts()

Result
0    101421
1     75665
Name: count, dtype: int64

In [15]:
df.head()

,Estimated Win Rate,Price,Customer Segment 1,Customer Segment 2,Customer Segment 3,Customer Segment 4,Customer Segment 5,Unit Number,Activity 1,Activity 2,Country,City,Product,Competitor,Marketing Source,Division,Result,Start_Year,Start_Month,Start_Day,Start_Weekday,End_Year,End_Month,End_Day,End_Weekday
0,0.75,3270.83,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021,3,16,1,2021,4,20,1
1,0.50,3772.74,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,2021,3,18,3,2021,8,16,0
2,0.10,2230.27,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021,4,1,3,2021,9,3,4
3,0.50,5000.00,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,2021,4,8,3,2021,7,1,3
4,0.20,51506.23,0,0,0,0,0,1,0,0,0,0,2,0,0,1,0,2021,3,17,2,2023,8,24,3

In [16]:
X = df.drop(columns=['Result'])
y = df['Result']

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [18]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=1000,depth=6,learning_rate=0.1,loss_function='Logloss',random_seed=42,verbose=100)
model.fit(X_train,y_train)

0:	learn: 0.4818861	total: 85.6ms	remaining: 1m 25s
100:	learn: 0.0353990	total: 2.36s	remaining: 21s
200:	learn: 0.0313326	total: 4.62s	remaining: 18.4s
300:	learn: 0.0289217	total: 6.78s	remaining: 15.7s
400:	learn: 0.0273296	total: 8.88s	remaining: 13.3s
500:	learn: 0.0259781	total: 11s	remaining: 11s
600:	learn: 0.0245372	total: 13.1s	remaining: 8.72s
700:	learn: 0.0234074	total: 15.2s	remaining: 6.49s
800:	learn: 0.0220164	total: 17.4s	remaining: 4.32s
900:	learn: 0.0210207	total: 19.4s	remaining: 2.13s
999:	learn: 0.0199110	total: 21.5s	remaining: 0us

In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

# Predict labels
y_pred = model.predict(X_valid)

# Predict probabilities for AUC
y_pred_proba = model.predict_proba(X_valid)[:, 1]

# Metrics
accuracy = accuracy_score(y_valid, y_pred)
precision = precision_score(y_valid, y_pred)
recall = recall_score(y_valid, y_pred)
f1 = f1_score(y_valid, y_pred)
auc = roc_auc_score(y_valid, y_pred_proba)
cm = confusion_matrix(y_valid, y_pred)
report = classification_report(y_valid, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC AUC:", auc)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", report)

Accuracy: 0.9909650460217968
Precision: 0.9867253729381613
Recall: 0.9922024714200753
F1 Score: 0.9894563426688633
ROC AUC: 0.9978231759575001
Confusion Matrix:
 [[20083   202]
 [  118 15015]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99     20285
           1       0.99      0.99      0.99     15133

    accuracy                           0.99     35418
   macro avg       0.99      0.99      0.99     35418
weighted avg       0.99      0.99      0.99     35418

In [20]:
test_df=pd.read_excel("/kaggle/input/buy-or-not-purchase-intent-prediction-challenge/Testing Dateset.xlsx")

In [21]:
test_df = test_df.reset_index(drop=True)

In [22]:
test_df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,ID,Start Date,End Date,Estimated Win Rate,Price,Customer Segment 1,Customer Segment 2,Customer Segment 3,Customer Segment 4,Customer Segment 5,Unit Number,Activity 1,Activity 2,Country,City,Product,Competitor,Marketing Source,Division,Manager,Techincal Manager,Customer ID,Result
0,177087,2018-02-11,2018-09-04,1.00,3000.000000,I,A,AA,CCC,AB,2.0,EF,IJ,GHI,LNO392,VUI150,NaN,JWP393,EM41,NaN,NaN,0017Q00001G4YkIQAV,NaN
1,177088,2018-11-14,2019-03-05,0.75,250000.000000,I,A,AA,CCC,AB,1.0,EF,IJ,GHI,LNO392,IEJ418,NaN,JWP393,QO91,NaN,NaN,0017Q00001G4YheQAF,NaN
2,177089,2024-05-16,2024-08-26,0.00,139677.231907,I,D,AA,CCC,AB,1.0,EF,IJ,PQR,FUH372,AHU981,UTG383,NaN,UW72,NaN,NaN,0017Q00001G4UAOQA3,NaN
3,177090,2023-02-09,2023-08-21,0.00,5194.576510,I,D,AA,CCC,AB,1.0,EF,IJ,MNO,DIF777,ASH122,SVE211,KAD664,EM41,NaN,NaN,0017Q00001OcHuHQAV,NaN
4,177091,2025-02-11,2025-12-31,0.00,132065.504490,I,A,AA,CCC,AB,1.0,EF,IJ,PQR,FUH372,AHU981,UTG383,RMD495,UW72,NaN,NaN,0017Q00001G4ZolQAF,NaN

In [23]:
Id = test_df.ID

In [24]:
test_df.drop(columns=["Manager","Techincal Manager","Customer ID","Result","ID"],axis=1,inplace=True)

In [25]:
test_df.isnull().sum()

Start Date                0
End Date                  0
Estimated Win Rate        0
Price                     0
Customer Segment 1        0
Customer Segment 2        0
Customer Segment 3        0
Customer Segment 4        0
Customer Segment 5        0
Unit Number            4291
Activity 1                0
Activity 2                0
Country                   0
City                   2998
Product                5357
Competitor            37515
Marketing Source       1041
Division                 16
dtype: int64

In [26]:
mode=test_df["City"].mode()[0]
test_df["City"]=test_df["City"].fillna(mode)


mode=test_df["Product"].mode()[0]
test_df["Product"]=test_df["Product"].fillna(mode)

mode=test_df["Competitor"].mode()[0]
test_df["Competitor"]=test_df["Competitor"].fillna(mode)

mode=test_df["Marketing Source"].mode()[0]
test_df["Marketing Source"]=test_df["Marketing Source"].fillna(mode)

mode=test_df["Division"].mode()[0]
test_df["Division"]=test_df["Division"].fillna(mode)


mode=test_df["Unit Number"].mode()[0]
test_df["Unit Number"]=test_df["Unit Number"].fillna(mode)

In [27]:
test_df['Start Date'] = pd.to_datetime(test_df['Start Date'])
test_df['End Date'] = pd.to_datetime(test_df['End Date'])

In [28]:
# From Start Date
test_df['Start_Year'] = test_df['Start Date'].dt.year
test_df['Start_Month'] = test_df['Start Date'].dt.month
test_df['Start_Day'] = test_df['Start Date'].dt.day
test_df['Start_Weekday'] = test_df['Start Date'].dt.weekday  # Monday=0

# From End Date
test_df['End_Year'] = test_df['End Date'].dt.year
test_df['End_Month'] = test_df['End Date'].dt.month
test_df['End_Day'] = test_df['End Date'].dt.day
test_df['End_Weekday'] = test_df['End Date'].dt.weekday

In [29]:
test_df.drop(columns=["Start Date","End Date"],axis=1,inplace=True)

In [30]:
cat_cols=test_df.select_dtypes(include=["object"]).columns

mappings = {}

for col in cat_cols:
    codes, uniques = pd.factorize(test_df[col])
    test_df[col] = codes
    mappings[col] = dict(enumerate(uniques))

# Show mappings for each column
for col, mapping in mappings.items():
    print(f"{col} mapping: {mapping}\n")

Customer Segment 1 mapping: {0: 'I', 1: 'F', 2: 'K', 3: 'H', 4: 'J', 5: 'G', 6: 'L'}

Customer Segment 2 mapping: {0: 'A', 1: 'D', 2: 'C', 3: 'B', 4: 'E'}

Customer Segment 3 mapping: {0: 'AA', 1: 'BB', 2: 'DD', 3: 'FF', 4: 'CC', 5: 'EE', 6: 'GG'}

Customer Segment 4 mapping: {0: 'CCC'}

Customer Segment 5 mapping: {0: 'AB', 1: 'CD'}

Activity 1 mapping: {0: 'EF'}

Activity 2 mapping: {0: 'IJ'}

Country mapping: {0: 'GHI', 1: 'PQR', 2: 'MNO', 3: 'ABC', 4: 'VWX'}

City mapping: {0: 'LNO392', 1: 'FUH372', 2: 'DIF777', 3: 'ISH651', 4: 'QGD703', 5: 'OHG455', 6: 'GHK468', 7: 'IKB920', 8: 'IQH555', 9: 'LJK362'}

Product mapping: {0: 'VUI150', 1: 'IEJ418', 2: 'AHU981', 3: 'ASH122', 4: 'WGG471', 5: 'OXC337', 6: 'SBS339', 7: 'DDH740', 8: 'TWV318', 9: 'VSY183', 10: 'WWQ705', 11: 'IYR218', 12: 'RWN676', 13: 'ELT244', 14: 'RPZ341', 15: 'UKC231', 16: 'ZZZ772', 17: 'TUH861', 18: 'JNQ525', 19: 'EFK842', 20: 'BZD102', 21: 'VTJ209', 22: 'UXG876', 23: 'BNX965', 24: 'YET951', 25: 'OQJ243', 26: 'LUU257', 27: 'QUJ298', 28: 'KFD575', 29: 'CYK149', 30: 'WFE973', 31: 'WQF420', 32: 'ACC683', 33: 'ZQP924', 34: 'ZRB471', 35: 'WGK163', 36: 'OQB899', 37: 'PBD708', 38: 'LMH911', 39: 'ZZG387', 40: 'IQN770', 41: 'RJX133', 42: 'PHK858', 43: 'BMO904', 44: 'TIB104', 45: 'SEQ701', 46: 'IGZ116', 47: 'TZU589', 48: 'QKL122', 49: 'PCS186', 50: 'GBA587', 51: 'PFE165', 52: 'AIH123', 53: 'OPJ875', 54: 'IDK592', 55: 'CAA301', 56: 'DJF344', 57: 'QPQ856', 58: 'VLQ786', 59: 'SWC918', 60: 'OUL192', 61: 'YHK552', 62: 'AIY965', 63: 'PDQ165', 64: 'HSI255', 65: 'MRG361', 66: 'IMI166', 67: 'XAZ377', 68: 'KFD782', 69: 'FAS572', 70: 'NVN460', 71: 'AHS534', 72: 'CSE619', 73: 'YRG284', 74: 'EIA804', 75: 'KWK188', 76: 'LQQ120'}

Competitor mapping: {0: 'SVE211', 1: 'UTG383', 2: 'WNQ578', 3: 'MWR693', 4: 'EYH512', 5: 'JRW278', 6: 'MAA248', 7: 'QDI149', 8: 'BTA951', 9: 'SYF894', 10: 'XXJ296', 11: 'GJS318', 12: 'JTS406', 13: 'BOT871', 14: 'NTE345', 15: 'BIA973', 16: 'UCM999', 17: 'BDZ984', 18: 'SIX191', 19: 'GPS257', 20: 'ZMR943', 21: 'IRM203', 22: 'AOV771', 23: 'LBB958', 24: 'ADL995', 25: 'QXP367', 26: 'PNC359', 27: 'JZQ408', 28: 'CIP753', 29: 'RRN963', 30: 'HPO378', 31: 'KTT271', 32: 'VIQ264', 33: 'HUN156', 34: 'FAN212', 35: 'YLN965', 36: 'HHY638', 37: 'DNM326', 38: 'IUI101', 39: 'WYC966', 40: 'NFZ970', 41: 'WNG820', 42: 'YMS626', 43: 'DEH909', 44: 'ZUJ180', 45: 'HAX691', 46: 'VVH130', 47: 'ZIR827', 48: 'UZQ547', 49: 'BVK186', 50: 'LIF565', 51: 'PPX925', 52: 'BAC277', 53: 'OZU499', 54: 'AUD215', 55: 'OZY811', 56: 'HDM269', 57: 'NOV834', 58: 'CBT270', 59: 'FJI920', 60: 'FMX428', 61: 'KDP510', 62: 'ZSN804', 63: 'VAA234', 64: 'LXG382', 65: 'NRF170', 66: 'UPC386', 67: 'FBT889', 68: 'VCM370', 69: 'MJD245', 70: 'GUI167', 71: 'QMB418', 72: 'MSC372', 73: 'UHL345', 74: 'ICT653', 75: 'OKH293', 76: 'DIN304', 77: 'MJD996', 78: 'YTO939', 79: 'ZPF594', 80: 'FKU295', 81: 'KTR678', 82: 'OQX525', 83: 'YYY958', 84: 'DIY342', 85: 'VOK166', 86: 'RZQ856', 87: 'SZC533', 88: 'OOT277', 89: 'YWU613', 90: 'PEM233', 91: 'CNB950', 92: 'NDH408', 93: 'CAS622', 94: 'FEI984', 95: 'CXE368', 96: 'OFG497', 97: 'UXI456', 98: 'GUC507', 99: 'LWU600', 100: 'LIW554', 101: 'ISF807', 102: 'XLX608', 103: 'MFH136', 104: 'BZP281', 105: 'NKR869', 106: 'ZLJ882', 107: 'KWE396', 108: 'DCJ484', 109: 'JFF572', 110: 'JWC127', 111: 'FCF899', 112: 'VEN624', 113: 'NVX755', 114: 'BLH766', 115: 'JZW339', 116: 'ZQJ711', 117: 'CAZ796', 118: 'CNY657', 119: 'QSG333', 120: 'KSX864', 121: 'BUS769', 122: 'JXT960', 123: 'TOD899', 124: 'UIU299', 125: 'NMZ646', 126: 'HPC410', 127: 'SVB937', 128: 'AYT362', 129: 'VQH661', 130: 'TPX566', 131: 'IAY453', 132: 'EQZ732', 133: 'FJU915'}

Marketing Source mapping: {0: 'JWP393', 1: 'KAD664', 2: 'RMD495', 3: 'FXW629', 4: 'ZDL229', 5: 'NEP704', 6: 'ZRG339', 7: 'DGO863', 8: 'GJG862', 9: 'QVB936', 10: 'XSX741', 11: 'QJE383', 12: 'VWV953', 13: 'QRY107', 14: 'URH199', 15: 'MHN746', 16: 'LZK497', 17: 'JLE804', 18: 'TMQ144', 19: 'BCL888'}

Division mapping: {0: 'EM41', 1: 'QO91', 2: 'UW72', 3: 'WF71', 4: 'PN73', 5: 'FY21', 6: 'YE43', 7: 'FA95', 8: 'FA29', 9: 'PY27', 10: 'DF88', 11: 'EU77', 12: 'OF62', 13: 'SX68', 14: 'JZ93', 15: 'XX96', 16: 'UT88', 17: 'MB97', 18: 'BP40', 19: 'GR79', 20: 'HU70', 21: 'HI71', 22: 'FU43', 23: 'WL88', 24: 'RZ94', 25: 'FT35', 26: 'CU52', 27: 'FN20', 28: 'AB49', 29: 'RU77', 30: 'DD49'}

In [31]:
test_df.head()

,Estimated Win Rate,Price,Customer Segment 1,Customer Segment 2,Customer Segment 3,Customer Segment 4,Customer Segment 5,Unit Number,Activity 1,Activity 2,Country,City,Product,Competitor,Marketing Source,Division,Start_Year,Start_Month,Start_Day,Start_Weekday,End_Year,End_Month,End_Day,End_Weekday
0,1.00,3000.000000,0,0,0,0,0,2.0,0,0,0,0,0,0,0,0,2018,2,11,6,2018,9,4,1
1,0.75,250000.000000,0,0,0,0,0,1.0,0,0,0,0,1,0,0,1,2018,11,14,2,2019,3,5,1
2,0.00,139677.231907,0,1,0,0,0,1.0,0,0,1,1,2,1,0,2,2024,5,16,3,2024,8,26,0
3,0.00,5194.576510,0,1,0,0,0,1.0,0,0,2,2,3,0,1,0,2023,2,9,3,2023,8,21,0
4,0.00,132065.504490,0,0,0,0,0,1.0,0,0,1,1,2,1,2,2,2025,2,11,1,2025,12,31,2

In [32]:
test_pred_proba = model.predict_proba(test_df)[:, 1]

test_pred_proba = (test_pred_proba >= 0.5).astype(int)
submission = pd.DataFrame({"ID": Id,"TARGET": test_pred_proba})

submission.to_csv("submission.csv", index=False)

In [33]:
df=pd.read_csv("/kaggle/working/submission.csv")

df.head()

       ID  TARGET
0  177087       1
1  177088       0
2  177089       0
3  177090       0
4  177091       0